// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918074156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            ProjectDescription = "Venison cow kielbasa porchetta tri-tip drumstick alcatra capicola. Cow tail alcatra swine frankfurter beef, meatball pork loin short ribs chislic chuck doner shank pig ham.",
                            ProjectName = "Onboarding UX Refresh"
                        },
                        new
                        {
                            Id = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            ProjectDescription = "Kielbasa drumstick frankfurter corned beef andouille prosciutto hamburger pork chop. Meatball brisket turducken t-bone pancetta.",
                            ProjectName = "Process Sync Initiative"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectTaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTaskStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProjectTaskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e79e1167-8ba5-4c8e-afe9-9b3dcf69df2a"),
                            AssignedUserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            ProjectTaskDescription = "Ham hock sirloin turducken venison. Picanha pork landjaeger, capicola meatloaf chuck pastrami ham hock. Alcatra ribeye frankfurter drumstick pork. ",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "- Audit Data Access Permissions\r\n"
                        },
                        new
                        {
                            Id = new Guid("724981b4-fe11-4247-8a51-2fdb56d16a50"),
                            AssignedUserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            ProjectId = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            ProjectTaskDescription = "Kielbasa beef tenderloin pastrami drumstick fatback pork chop. Short ribs ground round brisket, jerky pork chop porchetta biltong pancetta ham hock.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Conduct Vendor Risk Assessment"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectUser", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            UserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            UserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            UserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            Role = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            PasswordHash = "",
                            UserEmail = "maya.ellington@example.com",
                            UserName = "Maya Ellington"
                        },
                        new
                        {
                            Id = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            PasswordHash = "",
                            UserEmail = "luca.moretti@example.net",
                            UserName = "Luca Moretti"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedProjectTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.ProjectUser", b =>
                {
                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectTasks");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedProjectTasks");

                    b.Navigation("ProjectUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
