// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927124452_AddingSomeLoginStuff")]
    partial class AddingSomeLoginStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            ProjectDescription = "Venison cow kielbasa porchetta tri-tip drumstick alcatra capicola. Cow tail alcatra swine frankfurter beef, meatball pork loin short ribs chislic chuck doner shank pig ham.",
                            ProjectName = "Onboarding UX Refresh"
                        },
                        new
                        {
                            Id = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            ProjectDescription = "Kielbasa drumstick frankfurter corned beef andouille prosciutto hamburger pork chop. Meatball brisket turducken t-bone pancetta.",
                            ProjectName = "Process Sync Initiative"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            ProjectDescription = "Revamp the mobile app UI/UX for better engagement and retention.",
                            ProjectName = "Mobile App Redesign"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            ProjectDescription = "Migrate legacy systems to cloud infrastructure for scalability.",
                            ProjectName = "Cloud Migration"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-6c9d-0e1f-2a3b4c5d6e7f"),
                            ProjectDescription = "Centralize API management and security with a gateway solution.",
                            ProjectName = "API Gateway Implementation"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-7d0e-1f2a-3b4c5d6e7f8a"),
                            ProjectDescription = "Build a platform for advanced business intelligence and analytics.",
                            ProjectName = "Data Analytics Platform"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-8e1f-2a3b-4c5d6e7f8a9b"),
                            ProjectDescription = "Develop a self-service portal for customers to manage accounts.",
                            ProjectName = "Customer Portal Launch"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-9f2a-3b4c-5d6e7f8a9b0c"),
                            ProjectDescription = "Automate CI/CD pipelines and infrastructure provisioning.",
                            ProjectName = "DevOps Automation"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-0a3b-4c5d-6e7f8a9b0c1d"),
                            ProjectDescription = "Conduct a comprehensive security audit of all systems.",
                            ProjectName = "Security Audit"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-1b4c-5d6e-7f8a9b0c1d2e"),
                            ProjectDescription = "Upgrade HR software for improved payroll and benefits management.",
                            ProjectName = "HR System Upgrade"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-2c5d-6e7f-8a9b0c1d2e3f"),
                            ProjectDescription = "Expand e-commerce platform to new markets and regions.",
                            ProjectName = "E-commerce Expansion"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-3d6e-7f8a-9b0c1d2e3f4a"),
                            ProjectDescription = "Integrate AI-powered chatbot for customer support.",
                            ProjectName = "AI Chatbot Integration"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            ProjectDescription = "Implement marketing automation tools for campaigns.",
                            ProjectName = "Marketing Automation"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-5f8a-9b0c-1d2e3f4a5b6c"),
                            ProjectDescription = "Optimize inventory management using predictive analytics.",
                            ProjectName = "Inventory Optimization"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-6a9b-0c1d-2e3f4a5b6c7d"),
                            ProjectDescription = "Enable secure remote work for all employees.",
                            ProjectName = "Remote Work Enablement"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-7b0c-1d2e-3f4a5b6c7d8e"),
                            ProjectDescription = "Develop a tool to track regulatory compliance tasks.",
                            ProjectName = "Compliance Tracker"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-8c1d-2e3f-4a5b6c7d8e9f"),
                            ProjectDescription = "Create a system for employee performance reviews and feedback.",
                            ProjectName = "Performance Review System"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-9d2e-3f4a-5b6c7d8e9f0a"),
                            ProjectDescription = "Streamline supplier onboarding and management processes.",
                            ProjectName = "Supplier Management"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-0e3f-4a5b-6c7d8e9f0a1b"),
                            ProjectDescription = "Build an internal knowledge base for documentation and FAQs.",
                            ProjectName = "Knowledge Base"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-1f4a-5b6c-7d8e9f0a1b2c"),
                            ProjectDescription = "Plan and document incident response procedures for IT.",
                            ProjectName = "Incident Response Planning"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectTaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTaskStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProjectTaskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e79e1167-8ba5-4c8e-afe9-9b3dcf69df2a"),
                            AssignedUserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            ProjectTaskDescription = "Ham hock sirloin turducken venison. Picanha pork landjaeger, capicola meatloaf chuck pastrami ham hock. Alcatra ribeye frankfurter drumstick pork. ",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "- Audit Data Access Permissions\r\n"
                        },
                        new
                        {
                            Id = new Guid("724981b4-fe11-4247-8a51-2fdb56d16a50"),
                            AssignedUserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            ProjectId = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            ProjectTaskDescription = "Kielbasa beef tenderloin pastrami drumstick fatback pork chop. Short ribs ground round brisket, jerky pork chop porchetta biltong pancetta ham hock.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Conduct Vendor Risk Assessment"
                        },
                        new
                        {
                            Id = new Guid("a1e2f3d4-1a2b-4c3d-9e1f-1a2b3c4d5e6f"),
                            AssignedUserId = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            ProjectTaskDescription = "Create wireframes for the new mobile app redesign.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Design Mobile App Wireframes"
                        },
                        new
                        {
                            Id = new Guid("b2f3a4e5-2b3c-5d4e-8f2a-2b3c4d5e6f7a"),
                            AssignedUserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            ProjectId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            ProjectTaskDescription = "Draft migration plan for legacy systems.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Cloud Migration Planning"
                        },
                        new
                        {
                            Id = new Guid("c3e4b5f6-3c4d-6e5f-7a3b-3c4d5e6f7a8b"),
                            AssignedUserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            ProjectId = new Guid("c3d4e5f6-a7b8-6c9d-0e1f-2a3b4c5d6e7f"),
                            ProjectTaskDescription = "Set up API gateway and configure endpoints.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "API Gateway Setup"
                        },
                        new
                        {
                            Id = new Guid("d4f5c6a7-4d5e-7f6a-9b4c-4d5e6f7a8b9c"),
                            AssignedUserId = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            ProjectId = new Guid("d4e5f6a7-b8c9-7d0e-1f2a-3b4c5d6e7f8a"),
                            ProjectTaskDescription = "Develop dashboard for analytics platform.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Analytics Dashboard Development"
                        },
                        new
                        {
                            Id = new Guid("e5a6d7b8-5e6f-8a7b-1c5d-5e6f7a8b9c1d"),
                            AssignedUserId = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            ProjectId = new Guid("e5f6a7b8-c9d0-8e1f-2a3b-4c5d6e7f8a9b"),
                            ProjectTaskDescription = "Implement authentication for customer portal.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Customer Portal Authentication"
                        },
                        new
                        {
                            Id = new Guid("f6b7e8c9-6f7a-9b8c-2d6e-6f7a8b9c1d2e"),
                            AssignedUserId = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            ProjectId = new Guid("f6a7b8c9-d0e1-9f2a-3b4c-5d6e7f8a9b0c"),
                            ProjectTaskDescription = "Automate CI/CD pipeline for deployments.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "DevOps Pipeline Automation"
                        },
                        new
                        {
                            Id = new Guid("a7c8f9d0-7a8b-1c9d-3e7f-7a8b9c1d2e3f"),
                            AssignedUserId = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            ProjectId = new Guid("a7b8c9d0-e1f2-0a3b-4c5d-6e7f8a9b0c1d"),
                            ProjectTaskDescription = "Prepare checklist for security audit.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Security Audit Checklist"
                        },
                        new
                        {
                            Id = new Guid("b8d9a1e2-8b9c-2d1e-4f8a-8b9c1d2e3f4a"),
                            AssignedUserId = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            ProjectId = new Guid("b8c9d0e1-f2a3-1b4c-5d6e-7f8a9b0c1d2e"),
                            ProjectTaskDescription = "Migrate data to new HR system.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "HR System Data Migration"
                        },
                        new
                        {
                            Id = new Guid("c9e1b2f3-9c1d-3e2f-5a9b-9c1d2e3f4a5b"),
                            AssignedUserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            ProjectId = new Guid("c9d0e1f2-a3b4-2c5d-6e7f-8a9b0c1d2e3f"),
                            ProjectTaskDescription = "Analyze new market opportunities for e-commerce.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "E-commerce Market Analysis"
                        },
                        new
                        {
                            Id = new Guid("d0f2c3a4-0c1d-4e3f-6b0c-0c1d2e3f4a5b"),
                            AssignedUserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            ProjectId = new Guid("d0e1f2a3-b4c5-3d6e-7f8a-9b0c1d2e3f4a"),
                            ProjectTaskDescription = "Prepare training data for AI chatbot.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Chatbot Training Data"
                        },
                        new
                        {
                            Id = new Guid("e1a3d4b5-1d2e-5f4a-7c1d-1d2e3f4a5b6c"),
                            AssignedUserId = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            ProjectId = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            ProjectTaskDescription = "Set up marketing automation tools.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Marketing Automation Setup"
                        },
                        new
                        {
                            Id = new Guid("f2b4e5c6-2e3f-6a5b-8d2e-2e3f4a5b6c7d"),
                            AssignedUserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            ProjectId = new Guid("f2a3b4c5-d6e7-5f8a-9b0c-1d2e3f4a5b6c"),
                            ProjectTaskDescription = "Import inventory data for optimization.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Inventory Data Import"
                        },
                        new
                        {
                            Id = new Guid("a3c5f6d7-3f4a-7b6c-9e3f-3f4a5b6c7d8e"),
                            AssignedUserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            ProjectId = new Guid("a3b4c5d6-e7f8-6a9b-0c1d-2e3f4a5b6c7d"),
                            ProjectTaskDescription = "Draft remote work policy for employees.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Remote Work Policy Draft"
                        },
                        new
                        {
                            Id = new Guid("b4d6a7e8-4a5b-8c7d-1f4a-4a5b6c7d8e9f"),
                            AssignedUserId = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            ProjectId = new Guid("b4c5d6e7-f8a9-7b0c-1d2e-3f4a5b6c7d8e"),
                            ProjectTaskDescription = "Design UI for compliance tracker tool.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Compliance Tracker UI"
                        },
                        new
                        {
                            Id = new Guid("c5e7b8f9-5b6c-9d8e-2a5b-5b6c7d8e9f0a"),
                            AssignedUserId = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            ProjectId = new Guid("c5d6e7f8-a9b0-8c1d-2e3f-4a5b6c7d8e9f"),
                            ProjectTaskDescription = "Create template for performance reviews.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Performance Review Template"
                        },
                        new
                        {
                            Id = new Guid("d6f8c9a1-6c7d-0e9f-3b6c-6c7d8e9f0a1b"),
                            AssignedUserId = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            ProjectId = new Guid("d6e7f8a9-b0c1-9d2e-3f4a-5b6c7d8e9f0a"),
                            ProjectTaskDescription = "Prepare onboarding documentation for suppliers.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Supplier Onboarding Docs"
                        },
                        new
                        {
                            Id = new Guid("e7a9d0b2-7d8e-1f0a-4c7d-7d8e9f0a1b2c"),
                            AssignedUserId = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            ProjectId = new Guid("e7f8a9b0-c1d2-0e3f-4a5b-6c7d8e9f0a1b"),
                            ProjectTaskDescription = "Define structure for internal knowledge base.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Knowledge Base Structure"
                        },
                        new
                        {
                            Id = new Guid("f8b0e1c3-8e9f-2a1b-5d8e-8e9f0a1b2c3d"),
                            AssignedUserId = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            ProjectId = new Guid("f8a9b0c1-d2e3-1f4a-5b6c-7d8e9f0a1b2c"),
                            ProjectTaskDescription = "Draft playbook for incident response.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Incident Response Playbook"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-2a3b-4c5d-6e7f-8a9b0c1d2e3f"),
                            AssignedUserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            ProjectId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            ProjectTaskDescription = "Test mobile app features and report bugs.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Mobile App Testing"
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
                            AssignedUserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            ProjectId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            ProjectTaskDescription = "Execute migration of selected services.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Cloud Migration Execution"
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-4c5d-6e7f-8a9b-0c1d2e3f4a5b"),
                            AssignedUserId = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            ProjectId = new Guid("c3d4e5f6-a7b8-6c9d-0e1f-2a3b4c5d6e7f"),
                            ProjectTaskDescription = "Monitor API gateway traffic and errors.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "API Gateway Monitoring"
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            AssignedUserId = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            ProjectId = new Guid("d4e5f6a7-b8c9-7d0e-1f2a-3b4c5d6e7f8a"),
                            ProjectTaskDescription = "Validate analytics data sources.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Analytics Data Validation"
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-6e7f-8a9b-0c1d-2e3f4a5b6c7d"),
                            AssignedUserId = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            ProjectId = new Guid("e5f6a7b8-c9d0-8e1f-2a3b-4c5d6e7f8a9b"),
                            ProjectTaskDescription = "Collect feedback from portal users.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Customer Portal Feedback"
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-7f8a-9b0c-1d2e-3f4a5b6c7d8e"),
                            AssignedUserId = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            ProjectId = new Guid("f6a7b8c9-d0e1-9f2a-3b4c-5d6e7f8a9b0c"),
                            ProjectTaskDescription = "Review DevOps tools for automation.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "DevOps Tooling Review"
                        },
                        new
                        {
                            Id = new Guid("a8b9c0d1-8a9b-0c1d-2e3f-4a5b6c7d8e9f"),
                            AssignedUserId = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            ProjectId = new Guid("a7b8c9d0-e1f2-0a3b-4c5d-6e7f8a9b0c1d"),
                            ProjectTaskDescription = "Remediate issues found in audit.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Security Audit Remediation"
                        },
                        new
                        {
                            Id = new Guid("b9c0d1e2-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
                            AssignedUserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            ProjectId = new Guid("b8c9d0e1-f2a3-1b4c-5d6e-7f8a9b0c1d2e"),
                            ProjectTaskDescription = "Train staff on new HR system.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "HR System Training"
                        },
                        new
                        {
                            Id = new Guid("c0d1e2f3-0c1d-2e3f-4a5b-6c7d8e9f0a1b"),
                            AssignedUserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            ProjectId = new Guid("c9d0e1f2-a3b4-2c5d-6e7f-8a9b0c1d2e3f"),
                            ProjectTaskDescription = "Audit SEO for e-commerce platform.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "E-commerce SEO Audit"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-1d2e-3f4a-5b6c-7d8e9f0a1b2c"),
                            AssignedUserId = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            ProjectId = new Guid("d0e1f2a3-b4c5-3d6e-7f8a-9b0c1d2e3f4a"),
                            ProjectTaskDescription = "Test chatbot integration with support system.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Chatbot Integration Testing"
                        },
                        new
                        {
                            Id = new Guid("e2f3a4b5-2e3f-4a5b-6c7d-8e9f0a1b2c3d"),
                            AssignedUserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            ProjectId = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            ProjectTaskDescription = "Launch new marketing campaign.",
                            ProjectTaskStatus = 0,
                            ProjectTaskTitle = "Marketing Campaign Launch"
                        },
                        new
                        {
                            Id = new Guid("f3a4b5c6-3f4a-5b6c-7d8e-9f0a1b2c3d4e"),
                            AssignedUserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            ProjectId = new Guid("f2a3b4c5-d6e7-5f8a-9b0c-1d2e3f4a5b6c"),
                            ProjectTaskDescription = "Test inventory optimization system.",
                            ProjectTaskStatus = 1,
                            ProjectTaskTitle = "Inventory System Testing"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectUser", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            UserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            UserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            UserId = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            UserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("c3d4e5f6-a7b8-6c9d-0e1f-2a3b4c5d6e7f"),
                            UserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("d4e5f6a7-b8c9-7d0e-1f2a-3b4c5d6e7f8a"),
                            UserId = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("e5f6a7b8-c9d0-8e1f-2a3b-4c5d6e7f8a9b"),
                            UserId = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("f6a7b8c9-d0e1-9f2a-3b4c-5d6e7f8a9b0c"),
                            UserId = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("a7b8c9d0-e1f2-0a3b-4c5d-6e7f8a9b0c1d"),
                            UserId = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("b8c9d0e1-f2a3-1b4c-5d6e-7f8a9b0c1d2e"),
                            UserId = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            Role = 0
                        },
                        new
                        {
                            ProjectId = new Guid("15d4a262-aac1-418b-b32e-0bffd37966d5"),
                            UserId = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("37eac064-228b-45d8-bc19-9d09b94067b9"),
                            UserId = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            UserId = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            UserId = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("c3d4e5f6-a7b8-6c9d-0e1f-2a3b4c5d6e7f"),
                            UserId = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("d4e5f6a7-b8c9-7d0e-1f2a-3b4c5d6e7f8a"),
                            UserId = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("e5f6a7b8-c9d0-8e1f-2a3b-4c5d6e7f8a9b"),
                            UserId = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("f6a7b8c9-d0e1-9f2a-3b4c-5d6e7f8a9b0c"),
                            UserId = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("a7b8c9d0-e1f2-0a3b-4c5d-6e7f8a9b0c1d"),
                            UserId = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            Role = 1
                        },
                        new
                        {
                            ProjectId = new Guid("b8c9d0e1-f2a3-1b4c-5d6e-7f8a9b0c1d2e"),
                            UserId = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            Role = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be2f07b8-c92d-4138-b945-8fefecbc3cbe"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "maya.ellington@example.com",
                            UserName = "Maya Ellington"
                        },
                        new
                        {
                            Id = new Guid("6c8cd30a-cca3-4537-a8dd-7b6ac903bf29"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "luca.moretti@example.net",
                            UserName = "Luca Moretti"
                        },
                        new
                        {
                            Id = new Guid("a1e1c3d2-1b2a-4c3d-9e1f-1a2b3c4d5e6f"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "sofia.ivanova@example.org",
                            UserName = "Sofia Ivanova"
                        },
                        new
                        {
                            Id = new Guid("b2f2d4e3-2c3b-5d4e-8f2a-2b3c4d5e6f7a"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "james.oconnor@example.com",
                            UserName = "James O'Connor"
                        },
                        new
                        {
                            Id = new Guid("c3e3f5a4-3d4c-6e5f-7a3b-3c4d5e6f7a8b"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "aisha.patel@example.net",
                            UserName = "Aisha Patel"
                        },
                        new
                        {
                            Id = new Guid("d4f4a6b5-4e5d-7f6a-9b4c-4d5e6f7a8b9c"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "carlos.mendes@example.org",
                            UserName = "Carlos Mendes"
                        },
                        new
                        {
                            Id = new Guid("e5a5b7c6-5f6e-8a7b-1c5d-5e6f7a8b9c1d"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "emma.johansson@example.com",
                            UserName = "Emma Johansson"
                        },
                        new
                        {
                            Id = new Guid("f6b6c8d7-6a7f-9b8c-2d6e-6f7a8b9c1d2e"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "chen.wei@example.net",
                            UserName = "Chen Wei"
                        },
                        new
                        {
                            Id = new Guid("a7c7d9e8-7b8a-1c9d-3e7f-7a8b9c1d2e3f"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "fatima.alfarsi@example.org",
                            UserName = "Fatima Al-Farsi"
                        },
                        new
                        {
                            Id = new Guid("b8d8e1f9-8c9b-2d1e-4f8a-8b9c1d2e3f4a"),
                            PasswordHash = "",
                            RefreshToken = "",
                            UserEmail = "david.kim@example.com",
                            UserName = "David Kim"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedProjectTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.ProjectUser", b =>
                {
                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectTasks");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedProjectTasks");

                    b.Navigation("ProjectUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
